name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.1
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@joaovictor6'
      - name: Configure git
        run: |
          git config user.email "santosjoao.dev@gmail.com"
          git config user.name "João Victor"
      - run: pnpm install
      - run: pnpm rollup -c
      - run: pnpm version patch -m "Release %s 📣"
      - run: git push origin main
      - run: pnpm install --prod
      # publish
      - run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
